[package]
name = "advent-of-code-2024"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "day_1"
path = "src/bin/day_1/main.rs"

[dependencies]
ahash = "0.8.11"
nalgebra = "0.33.2"
regex = "1.11.1"
strum = { version = "0.26", features = ["derive"] }
strum_macros = "0.26"
